//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4EE.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S4EE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        public static string App_Language {
            get {
                return ResourceManager.GetString("App_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change ähnelt.
        /// </summary>
        public static string App_LanguageChange {
            get {
                return ResourceManager.GetString("App_LanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Settlers IV – Enhanced Edition Launcher ähnelt.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Settlers IV – Enhanced Gold Edition ähnelt.
        /// </summary>
        public static string App_Version_EGE {
            get {
                return ResourceManager.GetString("App_Version_EGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Settlers IV – Enhanced History Edition ähnelt.
        /// </summary>
        public static string App_Version_EHE {
            get {
                return ResourceManager.GetString("App_Version_EHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Settlers IV – Gold Edition ähnelt.
        /// </summary>
        public static string App_Version_GE {
            get {
                return ResourceManager.GetString("App_Version_GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Settlers IV – History Edition ähnelt.
        /// </summary>
        public static string App_Version_HE {
            get {
                return ResourceManager.GetString("App_Version_HE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die www.diesiedler4.de ähnelt.
        /// </summary>
        public static string App_Webseite {
            get {
                return ResourceManager.GetString("App_Webseite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlock missions? ähnelt.
        /// </summary>
        public static string MSB_Missionen {
            get {
                return ResourceManager.GetString("MSB_Missionen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlock all missions? ähnelt.
        /// </summary>
        public static string MSB_Missionen_Text {
            get {
                return ResourceManager.GetString("MSB_Missionen_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart of the app necessary! ähnelt.
        /// </summary>
        public static string MSB_Neutstart {
            get {
                return ResourceManager.GetString("MSB_Neutstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The application must be restarted to apply the settings. ähnelt.
        /// </summary>
        public static string MSB_Neutstart_Text {
            get {
                return ResourceManager.GetString("MSB_Neutstart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Supported ähnelt.
        /// </summary>
        public static string MSB_NotSupported {
            get {
                return ResourceManager.GetString("MSB_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Supported ähnelt.
        /// </summary>
        public static string MSB_NotSupported_Text {
            get {
                return ResourceManager.GetString("MSB_NotSupported_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S3 OK ähnelt.
        /// </summary>
        public static string MSB_S3 {
            get {
                return ResourceManager.GetString("MSB_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S3 OK ähnelt.
        /// </summary>
        public static string MSB_S3_Text {
            get {
                return ResourceManager.GetString("MSB_S3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play Videos? ähnelt.
        /// </summary>
        public static string MSB_Videos {
            get {
                return ResourceManager.GetString("MSB_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Should videos be played? ähnelt.
        /// </summary>
        public static string MSB_Videos_Text {
            get {
                return ResourceManager.GetString("MSB_Videos_Text", resourceCulture);
            }
        }
    }
}
