//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4EE.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S4EE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EDITION ähnelt.
        /// </summary>
        public static string App_Edition {
            get {
                return ResourceManager.GetString("App_Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CLASSIC ähnelt.
        /// </summary>
        public static string App_Edition_Classic_Title {
            get {
                return ResourceManager.GetString("App_Edition_Classic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ENHANCED GOLD EDITION ähnelt.
        /// </summary>
        public static string App_Edition_EGE {
            get {
                return ResourceManager.GetString("App_Edition_EGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ENHANCED HISTORY EDITION ähnelt.
        /// </summary>
        public static string App_Edition_EHE {
            get {
                return ResourceManager.GetString("App_Edition_EHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ENHANCED ähnelt.
        /// </summary>
        public static string App_Edition_Enhanced_Title {
            get {
                return ResourceManager.GetString("App_Edition_Enhanced_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GOLD EDITION (2003) ähnelt.
        /// </summary>
        public static string App_Edition_GE {
            get {
                return ResourceManager.GetString("App_Edition_GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HISTORY EDITION (2018) ähnelt.
        /// </summary>
        public static string App_Edition_HE {
            get {
                return ResourceManager.GetString("App_Edition_HE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We recommend the ENHANCED HISTORY EDITION for singleplayer and online multiplayer, 
        ///and the ENHANCED GOLD EDITION for local multiplayer (LAN). ähnelt.
        /// </summary>
        public static string App_Edition_Information_Text {
            get {
                return ResourceManager.GetString("App_Edition_Information_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die INFORMATION ähnelt.
        /// </summary>
        public static string App_Edition_Information_Title {
            get {
                return ResourceManager.GetString("App_Edition_Information_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DEINSTALL ähnelt.
        /// </summary>
        public static string App_Install_Deinstalliere {
            get {
                return ResourceManager.GetString("App_Install_Deinstalliere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DEINSTALLED ähnelt.
        /// </summary>
        public static string App_Install_Deinstalliert {
            get {
                return ResourceManager.GetString("App_Install_Deinstalliert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die INSTALL ähnelt.
        /// </summary>
        public static string App_Install_Installiere {
            get {
                return ResourceManager.GetString("App_Install_Installiere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die INSTALLED ähnelt.
        /// </summary>
        public static string App_Install_Installiert {
            get {
                return ResourceManager.GetString("App_Install_Installiert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DEUTSCH ähnelt.
        /// </summary>
        public static string App_Language_deDE {
            get {
                return ResourceManager.GetString("App_Language_deDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ENGLISH ähnelt.
        /// </summary>
        public static string App_Language_enUS {
            get {
                return ResourceManager.GetString("App_Language_enUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LANGUAGE ähnelt.
        /// </summary>
        public static string App_Language_Title {
            get {
                return ResourceManager.GetString("App_Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BUDDEL MAP PACK (by ramseslein) ähnelt.
        /// </summary>
        public static string App_Maps_B01 {
            get {
                return ResourceManager.GetString("App_Maps_B01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DEFEAT MAP PACK (by Sl4nger) ähnelt.
        /// </summary>
        public static string App_Maps_C01 {
            get {
                return ResourceManager.GetString("App_Maps_C01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die METZEL MAP PACK (by ramseslein) ähnelt.
        /// </summary>
        public static string App_Maps_M01 {
            get {
                return ResourceManager.GetString("App_Maps_M01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STANDARD UBISOFT MAPS ähnelt.
        /// </summary>
        public static string App_Maps_O01 {
            get {
                return ResourceManager.GetString("App_Maps_O01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STANDARD MAPS ähnelt.
        /// </summary>
        public static string App_Maps_Orignal {
            get {
                return ResourceManager.GetString("App_Maps_Orignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die REMASTERED SINGELPLAYER MAP PACK (by UltimateSpinDash) ähnelt.
        /// </summary>
        public static string App_Maps_R01 {
            get {
                return ResourceManager.GetString("App_Maps_R01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CAMPAIGN: ATLANTIS LEBT (2011) ähnelt.
        /// </summary>
        public static string App_Maps_S01 {
            get {
                return ResourceManager.GetString("App_Maps_S01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die THE SETTLERS TOURNAMENT 2020 MAPS ähnelt.
        /// </summary>
        public static string App_Maps_T01 {
            get {
                return ResourceManager.GetString("App_Maps_T01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die THE SETTLERS WORLD CHAMPIONSHIP 2021 MAPS ähnelt.
        /// </summary>
        public static string App_Maps_T02 {
            get {
                return ResourceManager.GetString("App_Maps_T02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BUDDEL ähnelt.
        /// </summary>
        public static string App_Maps_Title_BUDDEL {
            get {
                return ResourceManager.GetString("App_Maps_Title_BUDDEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die COOP ähnelt.
        /// </summary>
        public static string App_Maps_Title_COOP {
            get {
                return ResourceManager.GetString("App_Maps_Title_COOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die METZEL ähnelt.
        /// </summary>
        public static string App_Maps_Title_METZEL {
            get {
                return ResourceManager.GetString("App_Maps_Title_METZEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die REMASTERED ähnelt.
        /// </summary>
        public static string App_Maps_Title_REMASTER {
            get {
                return ResourceManager.GetString("App_Maps_Title_REMASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SINGLE PLAYER  ähnelt.
        /// </summary>
        public static string App_Maps_Title_SINGLEPLAYER {
            get {
                return ResourceManager.GetString("App_Maps_Title_SINGLEPLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TOURNAMENTS ähnelt.
        /// </summary>
        public static string App_Maps_Title_TOURNAMENTS {
            get {
                return ResourceManager.GetString("App_Maps_Title_TOURNAMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TRAINING ähnelt.
        /// </summary>
        public static string App_Maps_Title_TRAINING {
            get {
                return ResourceManager.GetString("App_Maps_Title_TRAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TRAIN MAP PACK (by ramseslein &amp; Sl4nger) ähnelt.
        /// </summary>
        public static string App_Maps_TR01 {
            get {
                return ResourceManager.GetString("App_Maps_TR01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EDITOR+ FIX (MAY HELP WHEN PROBLEMS OCCUR) ähnelt.
        /// </summary>
        public static string App_Misc_FIXES_EDITOR {
            get {
                return ResourceManager.GetString("App_Misc_FIXES_EDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TROUBLESHOOTING ähnelt.
        /// </summary>
        public static string App_Misc_FIXES_Title {
            get {
                return ResourceManager.GetString("App_Misc_FIXES_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LEGACY CONTROLS (HISTORY EDITION) ähnelt.
        /// </summary>
        public static string App_Misc_LEGACYCONTROLS {
            get {
                return ResourceManager.GetString("App_Misc_LEGACYCONTROLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ACTIVATE INEFFICIENT MINE WARNING ähnelt.
        /// </summary>
        public static string App_Misc_MINE {
            get {
                return ResourceManager.GetString("App_Misc_MINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UNLOCK ALL MISSIONS ähnelt.
        /// </summary>
        public static string App_Misc_MISSIONS {
            get {
                return ResourceManager.GetString("App_Misc_MISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AUTOSAVE EVERY 5 MINUTES (HISTORY EDITION) ähnelt.
        /// </summary>
        public static string App_Misc_SAVE_AUTOSAVE {
            get {
                return ResourceManager.GetString("App_Misc_SAVE_AUTOSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STORAGE ARCHIVES (older than 48 hours) ähnelt.
        /// </summary>
        public static string App_Misc_SAVE_SAVECLEANER {
            get {
                return ResourceManager.GetString("App_Misc_SAVE_SAVECLEANER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All saves of the selected edition will be moved to the archive folder after 48 hours.
        ///This keeps the game saves folder small. ähnelt.
        /// </summary>
        public static string App_Misc_SAVE_SAVECLEANER_Information_Text {
            get {
                return ResourceManager.GetString("App_Misc_SAVE_SAVECLEANER_Information_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SAVE SETTINGS ähnelt.
        /// </summary>
        public static string App_Misc_SAVE_Title {
            get {
                return ResourceManager.GetString("App_Misc_SAVE_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GAME SETTINGS ähnelt.
        /// </summary>
        public static string App_Misc_Title {
            get {
                return ResourceManager.GetString("App_Misc_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PLAY INGAME VIDEOS ähnelt.
        /// </summary>
        public static string App_Misc_VIDEO {
            get {
                return ResourceManager.GetString("App_Misc_VIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HOTKEYS MOD v2 (by Wizzardmaker &amp; kdsystem1337 - HISTORY EDITION) ähnelt.
        /// </summary>
        public static string App_Mod_Hotkeys {
            get {
                return ResourceManager.GetString("App_Mod_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MODS ähnelt.
        /// </summary>
        public static string App_Mod_Title {
            get {
                return ResourceManager.GetString("App_Mod_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EXTRA ZOOM MOD (by nyfrik) ähnelt.
        /// </summary>
        public static string App_Mod_Zoom {
            get {
                return ResourceManager.GetString("App_Mod_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die THE SETTLERS III MUSIC (additional) ähnelt.
        /// </summary>
        public static string App_Music_S3 {
            get {
                return ResourceManager.GetString("App_Music_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A installed Version of THE SETTLERS III HISTORY EDITION that has been started
        ///at least once is required. ähnelt.
        /// </summary>
        public static string App_Music_S3_Information_Text {
            get {
                return ResourceManager.GetString("App_Music_S3_Information_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MUSIC PACKS ähnelt.
        /// </summary>
        public static string App_Music_Title {
            get {
                return ResourceManager.GetString("App_Music_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die THE SETTLERS IV – ENHANCED EDITION LAUNCHER ähnelt.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NEW WORLD ADD-ON TEXTURES ähnelt.
        /// </summary>
        public static string App_Textures_NW {
            get {
                return ResourceManager.GetString("App_Textures_NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ORIGINAL TEXTURES ähnelt.
        /// </summary>
        public static string App_Textures_ORG {
            get {
                return ResourceManager.GetString("App_Textures_ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TEXTURE PACKS ähnelt.
        /// </summary>
        public static string App_Textures_Title {
            get {
                return ResourceManager.GetString("App_Textures_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DOWNLOAD COMPLETED - START INSTALLATION ähnelt.
        /// </summary>
        public static string App_Update_Abgeschlossen {
            get {
                return ResourceManager.GetString("App_Update_Abgeschlossen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DOWNLOAD ähnelt.
        /// </summary>
        public static string App_Update_Downlaod {
            get {
                return ResourceManager.GetString("App_Update_Downlaod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FATAL ERROR ähnelt.
        /// </summary>
        public static string MSB_Error {
            get {
                return ResourceManager.GetString("MSB_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unforeseen modification ähnelt.
        /// </summary>
        public static string MSB_Error_Mod {
            get {
                return ResourceManager.GetString("MSB_Error_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unforeseen modification to game files detected, please reset the game once to original state. ähnelt.
        /// </summary>
        public static string MSB_Error_Mod_Text {
            get {
                return ResourceManager.GetString("MSB_Error_Mod_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LACK OF RIGHTS ähnelt.
        /// </summary>
        public static string MSB_Error_Rechte {
            get {
                return ResourceManager.GetString("MSB_Error_Rechte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing rights. Please start the application as administrator. ähnelt.
        /// </summary>
        public static string MSB_Error_Rechte_Text {
            get {
                return ResourceManager.GetString("MSB_Error_Rechte_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FATAL ERROR - SOMETHING FAILED ähnelt.
        /// </summary>
        public static string MSB_Error_Text {
            get {
                return ResourceManager.GetString("MSB_Error_Text", resourceCulture);
            }
        }
    }
}
