//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S4EE.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S4EE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CLASSIC ähnelt.
        /// </summary>
        public static string App_Edition_Classic_Title {
            get {
                return ResourceManager.GetString("App_Edition_Classic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ENHANCED GOLD EDITION ähnelt.
        /// </summary>
        public static string App_Edition_EGE {
            get {
                return ResourceManager.GetString("App_Edition_EGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ENHANCED HISTORY EDITION ähnelt.
        /// </summary>
        public static string App_Edition_EHE {
            get {
                return ResourceManager.GetString("App_Edition_EHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ENHANCED ähnelt.
        /// </summary>
        public static string App_Edition_Enhanced_Title {
            get {
                return ResourceManager.GetString("App_Edition_Enhanced_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GOLD EDITION (2003) ähnelt.
        /// </summary>
        public static string App_Edition_GE {
            get {
                return ResourceManager.GetString("App_Edition_GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HISTORY EDITION (2018) ähnelt.
        /// </summary>
        public static string App_Edition_HE {
            get {
                return ResourceManager.GetString("App_Edition_HE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For online multiplayer we recommend the History Edition, for local games the Gold Edition. ähnelt.
        /// </summary>
        public static string App_Edition_Information_Text {
            get {
                return ResourceManager.GetString("App_Edition_Information_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die INFORMATION ähnelt.
        /// </summary>
        public static string App_Edition_Information_Title {
            get {
                return ResourceManager.GetString("App_Edition_Information_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
        /// </summary>
        public static string App_Language_de_DE {
            get {
                return ResourceManager.GetString("App_Language_de-DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        public static string App_Language_en_US {
            get {
                return ResourceManager.GetString("App_Language_en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Settlers IV – Enhanced Edition Launcher ähnelt.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NEW WORLD ADD-ON TEXTURES ähnelt.
        /// </summary>
        public static string App_Textures_NW {
            get {
                return ResourceManager.GetString("App_Textures_NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ORIGINAL TEXTURES ähnelt.
        /// </summary>
        public static string App_Textures_ORG {
            get {
                return ResourceManager.GetString("App_Textures_ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TEXTURE PACKS ähnelt.
        /// </summary>
        public static string App_Textures_Title {
            get {
                return ResourceManager.GetString("App_Textures_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fatal Error ähnelt.
        /// </summary>
        public static string MSB_Error {
            get {
                return ResourceManager.GetString("MSB_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fatal Error of App ähnelt.
        /// </summary>
        public static string MSB_Error_Text {
            get {
                return ResourceManager.GetString("MSB_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlock missions? ähnelt.
        /// </summary>
        public static string MSB_Missionen {
            get {
                return ResourceManager.GetString("MSB_Missionen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlock all missions? ähnelt.
        /// </summary>
        public static string MSB_Missionen_Text {
            get {
                return ResourceManager.GetString("MSB_Missionen_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S3 OK ähnelt.
        /// </summary>
        public static string MSB_S3 {
            get {
                return ResourceManager.GetString("MSB_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S3 OK ähnelt.
        /// </summary>
        public static string MSB_S3_Text {
            get {
                return ResourceManager.GetString("MSB_S3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play Videos? ähnelt.
        /// </summary>
        public static string MSB_Videos {
            get {
                return ResourceManager.GetString("MSB_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Should videos be played? ähnelt.
        /// </summary>
        public static string MSB_Videos_Text {
            get {
                return ResourceManager.GetString("MSB_Videos_Text", resourceCulture);
            }
        }
    }
}
